language: java
jdk:
  - openjdk14

sudo: false

env:
  global:
    CODECOV_TOKEN="edb1ddd4-6d9e-42d5-bc9d-91400cd560dd"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      -kiril5471710@gmail.com
    on_success: never # default: change
    on_failure: always # default: always