# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk14

services:
  - postgresql

before_install:
  - psql -c 'create database idea_db;' -U postgres
  - psql -c 'create database food;' -U postgres

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту youremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - kiril5471710@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
env:
  global:
    CODECOV_TOKEN="edb1ddd4-6d9e-42d5-bc9d-91400cd560dd"

